import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
  flex: 1,
  backgroundColor: '#0A0A0F',
  padding: 16,
  paddingBottom: 32,
  justifyContent: 'space-between',
},
  centered: {
    flex: 1,
    backgroundColor: '#0A0A0F',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
 title: {
  fontSize: 36,
  color: '#FF006E',
  letterSpacing: 6,
  fontFamily: 'BebasNeue_400Regular',
},
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  aliasText: {
    color: '#00F5FF',
    fontSize: 13,
    letterSpacing: 1,
  },
  rankingLink: {
    color: '#FFE600',
    fontSize: 13,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  logoutLink: {
    color: '#FF006E',
    fontSize: 13,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  backdropContainer: {
    borderRadius: 4,
    overflow: 'hidden',
    alignSelf: 'center',
  },
  hintsOverlay: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: 'rgba(10, 10, 15, 0.85)',
    borderRadius: 4,
    padding: 8,
    borderWidth: 1,
    borderColor: '#00F5FF',
    maxWidth: 200,
  },
  hintOverlayText: {
    color: '#00F5FF',
    fontSize: 11,
    letterSpacing: 1,
    marginBottom: 2,
  },
bottomContainer: {
  gap: 8,
  paddingBottom: 32,
},
skipButton: {
  alignSelf: 'center',
  paddingVertical: 10,
  paddingHorizontal: 32,
  borderRadius: 4,
  backgroundColor: '#FF006E',
  borderWidth: 0,
},
skipText: {
  color: '#FFFFFF',
  fontSize: 14,
  letterSpacing: 3,
  textTransform: 'uppercase',
  fontWeight: 'bold',
  fontFamily: 'BebasNeue_400Regular',
},
  loadingText: {
    color: '#888899',
    marginTop: 12,
    fontSize: 14,
    letterSpacing: 3,
    textTransform: 'uppercase',
  },
  errorText: {
    color: '#FF006E',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 16,
    letterSpacing: 1,
  },
  retryButton: {
    backgroundColor: '#FF006E',
    borderRadius: 4,
    paddingHorizontal: 24,
    paddingVertical: 12,
  },
  retryText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 14,
    letterSpacing: 3,
    textTransform: 'uppercase',
  },

});