import { StyleSheet } from 'react-native';

/**
 * Estilos de ResultView.
 * Estética cine años 80: neones, negro profundo y tipografía bold.
 */
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0A0A0F',
  },
  content: {
    padding: 24,
    gap: 16,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FF006E',
    letterSpacing: 6,
    textShadowColor: '#FF006E',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 12,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  aliasText: {
    color: '#00F5FF',
    fontSize: 13,
    letterSpacing: 1,
  },
  logoutLink: {
  color: '#FF006E',
  fontSize: 13,
  letterSpacing: 1,
  textTransform: 'uppercase',
},
  resultBanner: {
    borderRadius: 4,
    padding: 24,
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
  },
  winBanner: {
    backgroundColor: '#0A0A0F',
    borderColor: '#00F5FF',
    shadowColor: '#00F5FF',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 16,
    elevation: 8,
  },
  lossBanner: {
    backgroundColor: '#0A0A0F',
    borderColor: '#FF006E',
    shadowColor: '#FF006E',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 16,
    elevation: 8,
  },
  resultEmoji: {
    fontSize: 48,
  },
  resultTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#00F5FF',
    letterSpacing: 4,
    textShadowColor: '#00F5FF',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 12,
  },
  gameOverText: {
    fontSize: 48,
    fontWeight: 'bold',
    color: '#FF006E',
    letterSpacing: 6,
    textShadowColor: '#FF006E',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 20,
  },
  gameOverSub: {
    fontSize: 16,
    color: '#888899',
    letterSpacing: 4,
    textTransform: 'uppercase',
  },
  scoreBadge: {
    marginTop: 12,
    backgroundColor: '#0F0F1A',
    borderRadius: 4,
    paddingHorizontal: 24,
    paddingVertical: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FFE600',
    shadowColor: '#FFE600',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 10,
    elevation: 6,
  },
  scoreLabel: {
    color: '#FFE600',
    fontSize: 11,
    letterSpacing: 4,
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },
  scoreValue: {
    color: '#FFFFFF',
    fontSize: 48,
    fontWeight: 'bold',
    letterSpacing: 4,
  },
  movieCard: {
    backgroundColor: '#0F0F1A',
    borderRadius: 4,
    padding: 20,
    gap: 12,
    borderWidth: 1,
    borderColor: '#222233',
  },
  movieCardLabel: {
    color: '#888899',
    fontSize: 11,
    letterSpacing: 4,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  movieTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 4,
    letterSpacing: 1,
  },
  originalTitle: {
    fontSize: 13,
    color: '#888899',
    marginBottom: 8,
    letterSpacing: 1,
  },
  metaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#222233',
    paddingBottom: 8,
  },
  metaLabel: {
    color: '#00F5FF',
    fontSize: 13,
    fontWeight: 'bold',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  metaValue: {
    color: '#FFFFFF',
    fontSize: 13,
    flex: 1,
    textAlign: 'right',
  },
  primaryButton: {
    backgroundColor: '#FF006E',
    borderRadius: 4,
    paddingVertical: 14,
    alignItems: 'center',
    shadowColor: '#FF006E',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 12,
    elevation: 8,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: 'bold',
    letterSpacing: 4,
    textTransform: 'uppercase',
  },
  secondaryButton: {
    backgroundColor: 'transparent',
    borderRadius: 4,
    paddingVertical: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#00F5FF',
  },
  secondaryButtonText: {
    color: '#00F5FF',
    fontSize: 15,
    letterSpacing: 4,
    textTransform: 'uppercase',
  },
});